services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
        INSTALL_NPM_ASSETS: false
      secrets:
        - npmrc
    volumes:
      - '.:/src'
      - '/src/.venv'
      - '/src/node_modules'
      - '/src/static/assets'
    ports:
      - '8006:8006'
      - '5676:5676'
    depends_on: [ 'redis' ]
    networks:
        - default
        - mgo_vad

  redis:
    image: redis:6.2.17
    restart: 'no'
    ports:
      - '6379:6379'

  redis-init:
    depends_on: [ 'redis' ]
    image: redis:6.2.17
    restart: 'no'
    command: 'redis-cli -h redis set max:primary_identity_provider tvs'

  brp:
    container_name: brp
    image: ghcr.io/brp-api/personen-mock:2.3.0-latest
    environment:
        - ASPNETCORE_ENVIRONMENT=Release
        - ASPNETCORE_URLS=http://+:5010
    ports:
        - "5010:5010"
    networks:
        - mgo_vad

networks:
  mgo_vad:
    driver: bridge

secrets:
  npmrc:
    file: ~/.npmrc
