name: lint documentation
on:
  pull_request:
    paths:
      - 'docs/**/*.{md,markdown}'
      - '*.{md,markdown}'
jobs:
  mdlint:
    name: lint markDown file
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: DavidAnson/markdownlint-cli2-action@v19
      with:
        globs: |
          docs/**/*.{md,markdown}
          *.md

# https://github.com/DavidAnson/markdownlint
